version: '3'
services:
  app:
    image: 184571202268.dkr.ecr.ap-northeast-1.amazonaws.com/rails/rails-docker-webapp
    # build:
    #   context: .
    env_file:
      - ./environments/db.env
    command: bash -c "bundle exec puma -C config/puma.rb && rails webpacker:install"
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: myuser
      MYSQL_DATABASE: ecs_development
  web:
    image: 184571202268.dkr.ecr.ap-northeast-1.amazonaws.com/nginx/rails-docker-webapp:latest
    # build:
    #   context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
