default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db

development:
  <<: *default
  host: db
  username: myuser
  password: password
  database: ecs_development

# RDSに接続する用
# development:
#   <<: *default
#   host: <%= ENV['MYSQL_HOST'] %>
#   username: <%= ENV['MYSQL_USER'] %>
#   password: <%= ENV['MYSQL_PASSWORD'] %>
#   database: ecs_development

test:
  <<: *default
  database: webapp_test

production:
  <<: *default
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: ecs_development
